### ISSUE TITLE
undefined is not an object (evaluating 'n.core.get')

### ISSUE THREAD

**Issue by niugm** [dexie/Dexie.js#1071]
Hello, dexie is great, I used to develop im system data storage, when I upgraded to V3, found that the iOS system below 10.3 version of the below bug：

``` javascript
TypeError
undefined is not an object (evaluating 'n.core.get')
----------------------------------
Table.prototype.get = function (keyOrCrit, cb) {
    var _this = this;
    if (keyOrCrit && keyOrCrit.constructor === Object) return this.where(keyOrCrit).first(cb);
    return this._trans('readonly', function (trans) {
      return _this.core.get({   // throw error 
        trans: trans,
        key: keyOrCrit
      }).then(function (res) {
        return _this.hook.reading.fire(res);
      });
```
Is there a solution?  thanks

**Comment by dfahlander** [comment]
Check how you are calling Table.prototype.get(). Are you callling the function in an incorrect `this` context? Else, check if keyOrCrit is undefined when you call it. If so, this should have resulted in an error in previous versions of Dexie as well because undefined is not a valid key to get, but it may have given other error message.

**Comment by niugm** [comment]
> Check how you are calling Table.prototype.get(). Are you callling the function in an incorrect `this` context? Else, check if keyOrCrit is undefined when you call it. If so, this should have resulted in an error in previous versions of Dexie as well because undefined is not a valid key to get, but it may have given other error message.

Thank you for your reply and I will check my business code
