### ISSUE TITLE
How is Hosted Cloud Data Secured?

### ISSUE THREAD

**Issue by amxmln** [dexie/Dexie.js#1462]
Hi! First of all, let me say that as a long-time-fan of Dexie, Dexie Cloud seems like a dream come true. I’ve long been searching for a simple way to add syncing capabilities to an offline-first PWA without having to manage all that data and auth by myself.

I am wondering, however, how that data that will be stored on the hosted form of Dexie Cloud will be secured. Will it be encrypted so only users with access to it can read it? Will it be stored redundantly?

Thank you for your time and incredible efforts!

**Comment by dfahlander** [comment]
Thank you Amadeus for your nice words!

Dexie Cloud is backed by Postgres with encryption at rest, meaning that the data is stored encrypted on hard disks. I'm currently using Microsoft Azure's RDS service for Postgres which also includes continuous backups that makes sure data is stored redundantly in the case of hardware failure.

On top of the infrastructure, Dexie Cloud adds access control that protects users from accessing each other's data. This can be overridden dynamically per database object. The default is that every user works against their own data and everything they sync is private. To make objects shared between users, [realms](https://dexie.org/cloud/docs/access-control#realms) can be created and members can be invited to those realms. Any object can then be 'moved' into a realm by specifying the `realmId` property to the id of a realm in order to get them shared with the members of the realm. Most of the access control model can be read about [here](https://dexie.org/cloud/docs/access-control).

Access control is one thing that separates Dexie Cloud from alternative sync solutions where privacy needs to be implemented using one-database-per-user concepts. Some objects can be private while others can be shared in the same model and the same app. Much like it is in real world apps like Slack, Wunderlist, Jira etc.

There's an [example todo-list app written in React](https://github.com/dexie/Dexie.js/tree/master/samples/dexie-cloud-todo-app) that use Dexie Cloud to sync todo-lists. It uses a relational model with todoItems and todoLists tables and I'm currently extending that app so that users can create lists and share them with their friends.

I see you are on the waitlist for Dexie Cloud! When [milestone 3](https://dexie.org/roadmap/dexie-cloud#milestone-3---fully-functional-access-control-current) is out and todo-list sample has been updated, I plan to release more users into it from the wait list.

**Comment by amxmln** [comment]
Thank you for your quick and detailed reply David!

I’m looking forward to being able to try it out for myself when it’ll be my turn.
