### ISSUE TITLE
[liveQuery] Are changes propagated to service workers in browsers without BroadcastChannel?

### ISSUE THREAD

**Issue by otonashixav** [dexie/Dexie.js#1467]
If I'm reading it correctly, it seems that in browsers without BroadcastChannel, changes from windows and tabs only get propagated to other windows and tabs but not service workers: https://github.com/dexie/Dexie.js/blob/master/src/live-query/enable-broadcast.ts#L36-L45; shouldn't changes also be sent to service workers via `postMessage`?

**Comment by dfahlander** [comment]
Changes made in service worker are propagated to clients (windows/tabs) but not in the opposite direction. The reason is that service workers are not meant to be observing data as they are architected to live shortly. BroadcastChannel itself does not wake up service worker so even when it's supported, liveQuery would not be relyable in a service worker. If the SW happens to be awake, it would propagate, but if not, it would not wake up from a db mutation.

This design goes in have with how service workers are designed to be used - to do a job and then be done. 

This could be discussed off course. There might be use cases that would promote having service workers use liveQuery but if we must support it we would keep the service worker awake using postMessage rather than BroadcastChannel to communicate db changes to it ( to make sure it wakes up and consumed them). Still, it would be a bit strange because the live query could not possibly be listening when service worker is asleep 

Ideas and discussions welcome. If sticking to not recommend using liveQuery from within service workers, we should probably throw an Error when user does so, and if course document this limitation and the reason behind it.

**Comment by otonashixav** [comment]
Thanks for answering; I was unaware that service workers would timeout as they do.

**Comment by gotjoshua** [comment]
> to do a job and then be done
@dfahlander ,
is this the same for web workers?

**Comment by dfahlander** [comment]
> is this the same for web workers?

No, web workers are alive and never go to sleep as long as your app is loaded. However we do not polyfill live queries for browsers without service workers. The only modern browser missing the feature has been safari but it's implemented there as well now in Safari version 15.4.

**Comment by gotjoshua** [comment]
many thanks for the reply @dfahlander! hoping for more details on the new still open issue #1508 ...
