### ISSUE TITLE
Can't use Dexie in react-native

### ISSUE THREAD

**Issue by aguycalled** [dexie/Dexie.js#1473]
I am trying to use a library in react-native which depends on Dexie. By using `indexededdbshim` I intend to have `react-native-sqlite-2` as backend instead of IndexedDB.

```
import SQLite from 'react-native-sqlite-2';
import setGlobalVars from 'indexeddbshim/dist/indexeddbshim-noninvasive';
global.window = global;

setGlobalVars(null, {
  checkOrigin: false,
  win: SQLite,
  deleteDatabaseFiles: false,
  useSQLiteIndexes: true
});
```

Independently of the use of the `indexeddbshim` strategy, I see this error:

```ReferenceError: Can't find variable: addEventListener```

![image](https://user-images.githubusercontent.com/24814046/148688377-dc4bad10-4466-4ca0-a6ea-f883c4f43721.png)

Any clue on how to solve it?

**Comment by codemaster115** [comment]
I am also getting the same issue on React-Native(version 0.67).

**Comment by cmpayc** [comment]
The problem is in the wrong (incomplete) condition:
https://github.com/dexie/Dexie.js/blob/ad18b198ac6a2c87c2d45b2912b922bf1f5f275c/src/live-query/enable-broadcast.ts#L26-L63
`react-native` has a `navigator` property but no `addEventListener` function. 

Thus, it is necessary to add additional checks on `addEventListener`, as is done in the file `propagate-locally.ts`:
https://github.com/dexie/Dexie.js/blob/1c5576efa3fbb34856ece69345657ed8ddb8c5b3/src/live-query/propagate-locally.ts#L5-L22

Like:
```javascript
} else if (
  typeof self !== 'undefined' &&
  typeof navigator !== 'undefined' &&
  typeof dispatchEvent !== 'undefined' &&
  typeof addEventListener !== 'undefined'
) { 
```
