### ISSUE TITLE
dexie-cloud-todo-app — in some cases, initial sync hangs for about a minute

### ISSUE THREAD

**Issue by hangtwenty** [dexie/Dexie.js#1541]
I've encountered this on https://dexie.github.io/Dexie.js/dexie-cloud-todo-app/ in incognito mode, though I've also reproduced it locally (`yarn run build` then `npx serve ./build` then visit in an incognito tab) —  sometimes it hangs for a while trying to do the initial sync:

```
Service worker build on Fri Apr 01 2022 03:04:08 GMT-0700 (Pacific Daylight Time)
dexie-cloud-addon.js:2502 BroadcastedAndLocalEvent: bc.addEventListener() syncstatechanged-TodoDBCloud2-z0lesejpr bc is a BroadcastChannel
dexie-cloud-addon.js:5945 Dexie Cloud Addon: Using service worker
dexie-cloud-addon.js:4753 Performing initial sync
```

Eventually this appears in the logs, after which, sync succeeds: 

```
dexie-cloud-addon.js:4690 Latest initialSync worker seem to have died.
 The dead job started: Thu Apr 07 2022 16:59:12 GMT-0700 (Pacific Daylight Time) 
 Last heart beat was: Thu Apr 07 2022 16:59:12 GMT-0700 (Pacific Daylight Time) 
 We're now taking over!
```

I timed it a couple of times, and it seems to be a 60 second timeout. Maybe there's a way to detect the dead job sooner?

The interactive parts (i.e. creating a list) don't work while it's awaiting that initial sync.

----

When reproducing it on https://dexie.github.io/Dexie.js/dexie-cloud-todo-app/ it _seems_ like it happens consistently for the first incognito tab opened; but doesn't seem to happen outside of incognito (even when I unregister the service worker, "Clear Site Data" and close all tabs). Maybe just a coincidence but noting just in case.

----

If you want to reproduce it yourself, try a new incognito tab with https://dexie.github.io/Dexie.js/dexie-cloud-todo-app/ . You might also be able to see it by doing a local build, serving it, and opening in an incognito tab: `yarn run build && npx serve build`. 

Ah, and just confirmed that if I switch it to `serviceWorkerRegistration.unregister()`, the problem does not appear in the local build. However, if I keep `serviceWorkerRegistration.register()`, with `tryUseServiceWorker: false` in `db/TodoDB.ts`, the problem _does_ appear, though only in incognito.

**Comment by dfahlander** [comment]
Thanks for this finding!

I could reproduce this in non-incognito mode as well, in case of a true first experience (where the SW and databases where wiped out and the page has been refreshed after that to ensure they have no trace on the windows).

The reason seems to be due to some code in serviceWorkerRegistration.ts from workbox that does a page reload on the very first time it executes - and only when being served from localhost. The reload happens directly after the initial sync started and it aborts all JS execution and starts everything over again, leaving the "job" row in the DB that stalls the initial sync when executed the second time.

But I've realized that initialSync doesn't need to be protected using a *guarded job*. If it were to be executed multiple times in parallell, the only worst thing that could happen is some unnescessary double work - and no inconsistencies. So I will stop protecting initial sync whithin a guarded job. This will fix the issue. Thanks again for finding the issue!
