### ISSUE TITLE
useLiveQuery not working properly on Safari

### ISSUE THREAD

**Issue by kishkoigor** [dexie/Dexie.js#1573]
Found a bug, seems like useLiveQuery is not observing for db changes on Safari (both pc and mobile).
Made simple page with this case to reproduce the bug.

https://kishkoigor.github.io/dexie-worker-observe/

What's the case:
There is some Web Worker that updating existing entities in store and App.js that observing for changes with useLiveQuery and showing them.

If you open this page with Chrome or Mozilla, all seems ok, but for Safari useLiveQuery didn't catch it, but db still updating with worker.

**Comment by dfahlander** [comment]
BroadcastChannel support was added in Safari 15.4: https://caniuse.com/broadcastchannel

**Comment by kishkoigor** [comment]
So, tested it on Safari 14.1.2 (my current version), and Safari 15.3, 13.1, 12.1 on BrowserStack.

In all of this cases it's not working

**Comment by dfahlander** [comment]
Ok. Thanks for reporting. Can you confirm it works after upgrading to Safari 15.4?

**Comment by kishkoigor** [comment]
Just tested on Safari 15.5, and yes, it is working properly.

Is there any way to make this scenario work on older versions of Safari? Maybe some polyfill or trick?
Or one only way for me is not to rely on useLiveQuery and get data from db manually?

**Comment by dfahlander** [comment]
I just edited my earlier response about "the two reasons" why it isn't working. I did misinterpret the bug at first and didn't realize you were using a web worker to mutate the database. The thing is that in case you'd use a service worker instead of a web worker, it would had been working as we have a specific fallback for that. It is probably possible to do a similar workaround for web workers using something similar as we do in [enable-broadcast.ts](https://github.com/dexie/Dexie.js/blob/4d67d2bb206bf1f9bba620f0fc3e73226bd64e2f/src/live-query/enable-broadcast.ts). `globalEvent` can be replaced with `Dexie.on`. 

Without looking up the postMessage API between worker and web, it could conceptually be something like:
```ts
// In Worker:
let propagatingLocally = false;
Dexie.on('storagemutated', updatedParts => postMessage({type: "storagemutated", updatedParts}));
addEventListener('message', event => {
  if (event.data.type === 'storagemutated') {
    try {
      propagatingLocally = true;
      Dexie.on('storagemutated').fire(event.data.changedParts);
    } finally {
      propagatingLocally = false;
    }
  }
});

// Web
let propagatingLocally = false;
Dexie.on('storagemutated', updatedParts => myWorker.postMessage({type: "storagemutated", updatedParts}));
myWorker.addEventListener('message', event => {
  if (event.data.type === 'storagemutated') {
    try {
      propagatingLocally = true;
      Dexie.on('storagemutated').fire(event.data.changedParts);
    } finally {
      propagatingLocally = false;
    }
  }
});

```

**Comment by kishkoigor** [comment]
Okay, roger that!
I think, using service worker instead of window dedicated worker is not suitable for my task, but your "one way" example looks like exactly what I need.

Thank you for support, closing this issue
