### ISSUE TITLE
It will not sync with Cloud

### ISSUE THREAD

**Issue by maiernte** [dexie/Dexie.js#1625]
I build a Angular Application using Dexie Database Instance and sync with cloud, some thing like that

```

this.version(6).stores({
      test: '@id, title',
   });

this.cloud.configure({
      databaseUrl: "https://xxxxx.dexie.cloud",
      requireAuth: false,
      tryUseServiceWorker: true
    })
```

after I added some Data in the Dexie Database, try to open the Web in other Computer, but I can't got the SyncData. Even after the status is 'connected'

```
error: undefined
phase: "in-sync"
progress: undefined
status: "connected"
```

Can anyone help me out of this issue ?

**Comment by dfahlander** [comment]
When the user is unauthorized, client will not push local data to the server until the user authenticates. The reason is that there is no way for the server to know which user owns the data.

To authenticate a user, use this.cloud.login() to login a user. 

If you have [used the CLI to import](https://dexie.org/cloud/docs/cli#import) demo-users, use:

```ts
db.cloud.login({ grant_type: 'demo', demoUser })
```

If you want to prompt the user for email and one-time password (real user login):

```ts
db.cloud.login() // Will prompt user for email and then OTP
```

**Comment by dfahlander** [comment]
Hi again! A bug related to this was recently fixed in dexie-cloud-addon - that it may fail to sync the client data on login. The flow is as I described in previous response, but there was also a bug that prevented the offline data to be synced towards the server after a successful login. The bug is fixed in the latest version of dexie-cloud-addon (4.0.0-beta.24).
