### ISSUE TITLE
delete from compound index is slow if index is not pk index.

### ISSUE THREAD

**Issue by m12lrpv** [dexie/Dexie.js#1630]
I have a table with a number of indexes and about 1000 rows.
`messages: '[userId+typeId+id], [userId+typeId], [userId]`

This delete against the pk is instant (< 100ms)
```
        let deleteCount = await myApp.messages
            .where(['userId+typeId+id'])
            .between([userIdValue, typeIdValue, Dexie.minKey], [userIdValue, typeIdValue, Dexie.maxKey], true, true)
            .delete();
```

This delete against the non PK compound index takes 7 seconds for 500 rows.
```
        let deleteCount = await myApp.messages
            .where(['userId+typeId'])
            .equals([userIdValue, typeIdValue])
            .delete();
```

By contrast this delete against a non compoind third index is instant.
```
        let deleteCount = await myApp.messages
            .where(['userId'])
            .equals([userId])
            .delete();
```

The second query, even though it is an exact match on an index is slow for deletes only. For select queries it is instant.

**Comment by dfahlander** [comment]
**Short answer**

Bump version number, remove the indexes and declare only the primary key. All three queries will still work but all will be fast:

```ts
{ messages: '[userId+typeId+id]' }
```

**Long answer**

The reason for the behavior is this: IndexedDB has a native range delete on primary keys but not on indexes. Dexie will chose the native fast range deletion whenever possible - when using primary key range, but cannot do so when using an index. 

Good news is that if you're on dexie version >=3.2.0, you don't even need those extra indexes anyway as they are already covered by the primary key. Dexie >= 3.2.0 can emulate parts of compound primary key or index as if it was declared as its own index. So try to just add a new version where you only specify the compound primary key and omit the indexes:

All three queries will still work, but now, they can all utilize the native range deletion instead. The magic behind this lies in [virtual-index-middleware.ts](https://github.com/dexie/Dexie.js/blob/master/src/dbcore/virtual-index-middleware.ts).

The reason the third query also was fast, was that an it used array brackets around the non-compound index 'userId' an index that shouldn't have brackets, so it probably triggered the virtual index middleware to use the primary key instead.

**Comment by m12lrpv** [comment]
Sorry but I've spent the last 6 weeks implementing dexie into an angular solution and would have to **disagree** with your assertion due to the bug https://github.com/dexie/Dexie.js/issues/939 that still exists.

The indexes are needed to enable where to be used and make dexie work at all.

**Comment by dfahlander** [comment]
> Sorry but I've spent the last 6 weeks implementing dexie into an angular solution and would have to **disagree** with your assertion due to the bug #939 that still exists.
> 
> The indexes are needed to enable where to be used and make dexie work at all.

I don't know if you fully understood my last answer - the indexes are redundant because dexie can reuse the leading parts of the primary key as indexes. Every time you declare a compound primary key or property, such as `[userId+typeId+id]`, you implicitly get the partial virtual indexes for free: `[userId+typeId], userId` and you can use them in where-clauses such as `db.messages.where('[userId+typeId]').equals(["x", "y"])` or `db.messages.where({userId: 'x', typeId: 'y'})`.

So you can basically do the following, and it would be more performant as the virtual indexes are based on the primary key, which is faster on range deletions, especially on angular with zonejs slowing down the IndexedDB performance, as described in #939 :

```ts
const db = new Dexie('dbname');
db.version(2).stores({
  messages: '[userId+typeId+id]'
});

function deleteMessagesFor(userId: string, typeId?: string) {
  return typeId
    ? db.messages.where({userId, typeId}).delete()
    : db.messages.where({userId}).delete(); 
}
```

Try this! Both of the 2 deletion queries will be forced to use the primary key for the deletion. If you had added the explicit indexes, they would chose them instead and not be as fast.
