### ISSUE TITLE
Update the Collection.filter type to be similar to Array.filter

### ISSUE THREAD

**Issue by Kreash** [dexie/Dexie.js#1657]
Update the Collection.filter type to be similar to Array.filter.
By adding "value is S" to the return value so that it is possible to change the type after filtering

The current state of the type `Collection.filter: filter(filter: (x: T) => boolean): Collection<T, TKey>;`
Desired state of type Collection.filter: `filter<S extends T>(filter: (value: T) => value is S): Collection<S, TKey>;`

**Comment by Kreash** [comment]
I created a pull request to solve this problem: https://github.com/dexie/Dexie.js/pull/1658

**Comment by dfahlander** [comment]
Thanks, this sounds logical and I wish it worked but I can't see the change make any difference in practice. As far as I know, not even Array.prototype.filter() can properly filter out by inferring the filter function to a return value that extends T but is more precise.

I would love to see this work for both Array.filter and Collection.filter():

```ts
type Thing = Foo | Bar;

interface Bar {
   type: "bar"
   barProp: string;
}

interface Foo {
   type: "foo";
   fooProp: number;
}

const a: Thing[] = [{
  type: "foo",
  fooProp: 1
}, {
  type: "bar",
  parProp: "hey!"
}];

a.filter(x => x.type === "foo")[0].fooProp; // Compile error: Property 'fooProp' does not exist on type Thing;
```
I still get error in standard typescript Array.filter (see above) but I wish it would work.

Do you have an example code snipped that could show how this would work? I agree with the code but don't find it work as expected due to some typescript limitation.

**Comment by Kreash** [comment]
If the filter function is passed a predicate of the following form: (value: T): value is S => return boolean 
Then at the output we get a filtered type S

In the case shown below, the Animal type becomes the Dog type:
```typescript
interface Animal {
  name: string;
  age: number;
}

interface Dog extends Animal {
  woof: () => void;
}

function isDog(animal: Animal): animal is Dog {
  return animal.hasOwnProperty("woof");
}

function woofIfDog(animals: Animal[]) {
  const dogs: Dog[] = animals.filter(isDog);
  dogs.forEach((dog: Dog) => dog.woof());
}

const animalsArray = [
  { name: "Fido", age: 4, woof: () => console.log("woof") },
  { name: "Whiskers", age: 15, meow: () => console.log("meow") },
];

woofIfDog(animalsArray);
```

**Comment by Kreash** [comment]
To make it work in your example, you need to change the filter call like this:
```typescript
function isFoo(x: Thing): x is Foo {
  return x.type === "foo";
}

a.filter(isFoo)[0].fooProp;
```

**Comment by dfahlander** [comment]
Nice that it can be achieved, though with explicit `is` declaration. And of course worth it to merge this PR!
