### ISSUE TITLE
DexieCloud - initial sync not working

### ISSUE THREAD

**Issue by b-straub** [dexie/Dexie.js#1721]
Initial sync after invitation has issues.

To reproduce:

- ToDo sample
- empty database
- login Alice on Browser 1
- login Bob on Browser 2
- create AliceList on Alice
- create AliceItem on Alice
- invite Bob
- accept invitation on Bobs side
- complete AliceItem on Alice side -> not synced!
- uncomplete AliceItem  on Alice side
- complete AliceItem on Bobs side -> not synced!
- logout Alice
- logout Bob
- login Alice
- login Bob
- two way sync works now

**Comment by dfahlander** [comment]
Thanks for a nice repro! I got a similar report from another customer. It's probably due to the rewrite of these stuff I did for a few weeks ago. Hope to get time to dive into this next week at latest (I'm at the moment in the end of the tunnel of PR #1718)

**Comment by dfahlander** [comment]
Hi! I've finally been able to following your steps after a few bug fixes having been done on dexie optimistic updates features. The todo-list sample is now on dexie@4.0.1-alpha.22 with the latest fixes and following your repro steps works now without any issues. Don't know exactly where the issue was but it could have been related to cache/optimistic updates.

I did follow the repro exactly on various combinations of browsers:

* Alice on desktop chrome app. Bob on chrome with different profile
* Alice on Safari. Bob on Chrome.
* Alice on Chrome. Bob on Safari.

It seems very stable and fast right now with dexie@4.0.1-alpha.22, dexie-cloud-addon@4.0.1-beta.40 and dexie-react-hooks@1.1.6.

The deployed sample app at https://dexie.github.io/Dexie.js/dexie-cloud-todo-app/ has the latest dependencies and been redeployed recently.

If you'd have any chance to verify it from your side, please do. Should there be anything I've got wrong feel free to reopen the issue!
