### ISSUE TITLE
liveQuery trigger delay 35-50ms after Write

### ISSUE THREAD

**Issue by scazzy** [dexie/Dexie.js#1722]
Dexie is heavily integrated in our app and I was removing our own DataChangeRecord observable logic to use liveQuery as both does the same thing. 
One thing that stands out is time delay that liveQuery observable triggers once the data is written in IDB.
While writes usually are taking around `8-10ms`, the time difference from when the write has completed and the liveQuery observable was triggered is hovering around `35-50ms`, which is very significant if I'm relying to update data based on the observable.

Looking for pointers on 
1) why this delay is high
2) how can we optimize this
3) where should I look at in the code? I checked liveQuery module and nothing stood out

**Comment by dfahlander** [comment]
Hi! The time delay is the sum of the write-transaction and the re-executed read operations. If there are many components reading the same data they will all rerun their querier and query indexeddb for the same data - each one with its own IndexedDB request - which may make it take longer time if there are many components that react to the write transaction and starts reading over again.

Good news is that a new pull request (#1718) will speed up most liveQueries significantly.

The PR #1718 includes:

* Optimistic updates: A cache keeps track of the latest results of each query and generate optimistic updates directly when mutating the database and before the transaction commit. Should operation or transaction fail, optimistic updates are rolled back. Querier callbacks are still reexecuted but their queries will get immediate response from the cache with optimistic updates applied on top.
* Reuse of data: If having many components using liveQuery on the same data, they will be able to reuse the cached results from other queries. This means significant performance gain when components query the same data.

The new cache and optimistic updates are part of the [road map](https://dexie.org/roadmap/dexie4.0). A new beta release will soon be available to test (within a week). It will be improved step-by-step:

First version (implemented already and passes most tests): Optmize all `toArray()` queries with or without where clauses on operators above, below, aboveOrEqual, belowOrEqual, between, equals and startsWith. Not equalsIgnoreCase nor anyOf etc. Not offset based queries (paging).

Coming versions will support get(), bulkGet() and count() queries, offset/limit queries. It will also be able to reuse similar queries (supersets and neighboring pages) instead of just matching equal queries.

I'm looking so much forward to releasing this and improving it step-by-step. Queries not being able to cache are IDBCursor based queries (anyOf(), equalsIgnoreCase(), and some more). They will also get this optimization eventually when the richer query engine is in place.

Another implied change is that Dexie will be moving to returning immutable, frozen data so that we can return data directly from the cache without having to clone it - this is configurable though - but the default configuration will probably be `{cache: 'immutable'}` to encourage users to treat response data as immutable because that gives a performance gain over the other option `{cache: 'cloned'}`. There is also a third option `{cache: 'disabled'}` that disable the cache and the optimistic updates in whole.

**Comment by scazzy** [comment]
@dfahlander the roadmap says the cache will be in place for non-transactional queries, where as all/most write queries people write are within transactions.  Would this mean it'll the optimistic updates to cache will not be helpful with transactions?

**Comment by dfahlander** [comment]
That is about the read transactions - All operations inside or outside a write transactions will directly affect the any live queries that do not use explicit read transactions in them. All the unit tests in dexie itself pass now but I'm debugging the unit tests of dexie-react-hooks that indicates there's still some issue. There's an informal release that includes this if you'd like to test - but expect a few new versions coming out during the coming week. Current one with the change is dexie@4.0.1-alpha.11 (but it has some issues right now).

I mentioned in the last comment that dexie would move over to immutable data. After thinking it through, I decided not to enforce that change upon users and instead keep returning mutable data to the users, but allow opt-in to immutable data for improved performance and memory footprint (using constructor option `{ cache: 'immutable' }`). The default value is `{ cache: 'cloned' }` and it's also possible to opt-out with `{ cache: 'disabled' }`.

**Comment by scazzy** [comment]
Thanks for clarification. Will close this as an issue.
