### ISSUE TITLE
liveQuery(): second call of caller function in non-frontend components

### ISSUE THREAD

**Issue by CaptainChaos** [dexie/Dexie.js#1771]
I am using liveQuery in a non-frontend class (with dexie alpha v4 25), and from what I observed I assume liveQuery() calls the calling function a second time before the liveQuery is actually created. I could not find help in the docs on how to prevent this or what alternative methods I can use to achieve the same thing without that extra function call - having an observable which I can subscribe to. It should do nothing other than calling the next function on initial and subsequent data, while also having the nice multi tab compatibility liveQuery offers.

Is the behaviour regarding the second function call expected, or might this be an issue on my end? Would it help to always wrap the liveQuery call into an anonymous function, like (() => liveQuery(...))(), to have a simple fix?

Or is liveQuery not the right function here, and would this be something I'd do with dbCore / Dexie.use() ? I can't find a good entry point where to start.

**Comment by CaptainChaos** [comment]
One additional question: Is it possible that the liveQuery observable triggers multiple times during transactions? If so, could I also circumvent this with digging deeper into dbCore, or is there any other way to do this?

**Comment by dfahlander** [comment]
> I am using liveQuery in a non-frontend class (with dexie alpha v4 25), and from what I observed I assume liveQuery() calls the calling function a second time before the liveQuery is actually created. I could not find help in the docs on how to prevent this or what alternative methods I can use to achieve the same thing without that extra function call - having an observable which I can subscribe to. It should do nothing other than calling the next function on initial and subsequent data, while also having the nice multi tab compatibility liveQuery offers.
> 
> Is the behaviour regarding the second function call expected, or might this be an issue on my end? Would it help to always wrap the liveQuery call into an anonymous function, like (() => liveQuery(...))(), to have a simple fix?
> 
> Or is liveQuery not the right function here, and would this be something I'd do with dbCore / Dexie.use() ? I can't find a good entry point where to start.

It's not expected that a new observable returned from liveQuery() would call the querier before someone subscribes to the observable. When someone calls .subscribe() on the observable, it will immediately call the querier callback once and after that whenever a mutation happens that affects the result of the query.

> One additional question: Is it possible that the liveQuery observable triggers multiple times during transactions? If so, could I also circumvent this with digging deeper into dbCore, or is there any other way to do this?

If you are on 3.x or 4.x with [{cache: 'disabled'}](https://dexie.org/docs/Dexie/Dexie) option to dexie constructor, liveQueries only get triggered after a write transaction successfully commits. If you are on dexie 4.x (dexie@next), the default behavior is to trigger liveQueries optimistically on every write operation but it stays away from re-executing the liveQuery again when transaction commits (but if it fails, it will re-execute the liveQuery with the rolled back value).

Don't know why you are observing the dublicate callbacks on a pure liveQuery observable. There's been one recently solved issue though (in both 3.x and 4.x) that the react hooks `useLiveQuery()` and `useObservable` did do an unnescessary temporary subscribe to the observable on initial render making them be called one unnescessary time (see https://github.com/dexie/Dexie.js/releases/tag/v3.2.4). Since you are not in frontend code, I suppose that is not the case for you though.

As the behavior you describe is not expected - it might be a good idea to try surround it in a stand-alone repro code (on jsitor.com for example) that you could post to this ticket to help either to pin point an error in how it is being used or to hunt down a possible bug in dexie)

**Comment by CaptainChaos** [comment]
I set up a standalone repo (also with dexie v4 alpha 25) and could not reproduce the issue - my mistake was assuming that the next() call does not happen synchronously on subscribe. That must have been what called the function again, since I do some things in there. Thank you, also for the help regarding the transaction behaviour!
