### ISSUE TITLE
When would `anyOf()` be supported with optimistic updates?

### ISSUE THREAD

**Issue by rayzhao99** [dexie/Dexie.js#1772]
Optimistic updates might be quite helpful in our scenarios, since  a great amount of records might be loaded within a single liveQuery(), which might be up to hundreds of thousands, and even up to millions. However, optimistic updates do not support `anyOf()`, as well as some other queries but `anyOf()` is widely used in our codes. 

So, would you please share the schedule on when more queries will be supported?

**Comment by dfahlander** [comment]
Hi Zhao,

I'm glad you had use for the optimistic updates! Optimistic updates needed some time to become stable before I would extend it to more queries. I now consider it stable after having gone through a bunch of patch-releases before finally working well, so it would be perfect time to extend it now, but focus of all development is currently to get Dexie Cloud into official production before end of summer (at last). Plan is to focus on optimistic updates again after that and also continue on some other parts of the 4.0 roadmap in parallell with further Dexie Cloud development.

Until `anyOf()` supports optimistic updates, it can be implemented using a function that uses Promise.all() with several equal queries (which might be an optimization in itself, and probably the solution that will go into dexie):

```ts
import { type Table from 'dexie' };

export async function anyOf<T,K,I>(table: Table<T,K,I>, index: string, keys: any[]): Promise<T[]> {
  const resultArrays = await Promise.all(
    keys.map(key => table.where(index).equals(key).toArray())
  );
  return resultArrays.flat(1);
}
```

**Comment by rayzhao99** [comment]
Got it, and your solution sounds working for our scenarios. Thanks!

**Comment by rayzhao99** [comment]
Well, some other questions, 
1. with the `anyOf()` implemented above, some records might meet more than one equal queries at the same time. So, will the records be loaded and instantiated for multiple times, or for only once with the help of optimistic updates?
2. if unsubscribed the observable returned by `liveQuery()`, and launching another `liveQuery()` after that, will the second `liveQuery()` benefit from the cache initialized by the first one? I mean, will the cached records be released once after the corresponding `liveQuery()` has been unsubscribed and finished?

**Comment by dfahlander** [comment]
Good questions and yes, as you've noticed, there's a difference in the results if the keys passed to anyOf have duplicates. There's also a difference in sorting. Sorting can be fixed by sorting (array.sort()) and eliminating duplicates keys (for example passing keys into a set and back) before Promise.all(). *If keys are non-strings or non-numbers (arrays, binary or Dates), sorting has to be made using Dexie's cmp() function and set won't work. You could then import { RangeSet } from dexie and use addKeys() into it and extracting them to array again using `[...rangeSet].map(treeNode => treeNode.from)`.*


> 1. with the `anyOf()` implemented above, some records might meet more than one equal queries at the same time. So, will the records be loaded and instantiated for multiple times, or for only once with the help of cache and optimistic updates?

If the liveQuery performs a number of queries within it, as in this case using Promise.all(), each one of them will utilize the cache and respond immediately if the query has been queried before.

> 2. if unsubscribed the observable returned by `liveQuery()`, and launching another `liveQuery()` after that, will the second `liveQuery()` benefit from the cache initialized by the first one? I mean, will the cached records be released once after the corresponding `liveQuery()` has been unsubscribed and finished?

The cache is kept alive as long as there are subscriptions going on - be it one or multiple. When the last subscription of a query is released, there's a grace period of 3000 milliseconds before the cache is cleared out. If any more subscription is started against the same query during that grace period, it will be kept alive, but if not, it will be released from the cache.

**Comment by rayzhao99** [comment]
So, though duplicates will be returned, they will only be loaded once. And the returned are the same instance from the cached, no matter they are loaded within the same query or from different queries. Is this right?

**Comment by dfahlander** [comment]
> So, though duplicates will be returned, they will only be loaded once. And the returned are the same instance from the cached, no matter they are loaded within the same query or from different queries. Is this right?

True if using ’{ cache: 'immutable' }’ in options to Dexie constructor. Otherwise if using default ’{ cache: 'cloned' }’, also true except that every returned result from cache with be a cloned unique instance, but loaded directly from cache.

**Comment by rayzhao99** [comment]
Quite clear, thanks so much! Nice feature:)
