### ISSUE TITLE
Cloud REST API: Updated user properties are not propagated

### ISSUE THREAD

**Issue by b-straub** [dexie/Dexie.js#1854]
### Cloud REST API: Updated user properties are not propagated.

I updated the _evalDaysLeft_ property for a user via the REST API and verified the success by another users data poll.
I expected the _db.cloud.currentUser_ observable to trigger an event after the update, but this was not the case.
After logging out, logging in the same user the new _evalDaysLeft_ value was visible.

All changes made by the REST API should be propagated right away.

**Comment by dfahlander** [comment]
Hi! Unlike other application data, properties on the users are not designed to be eagerly propagated. The reason is that the data comes from the token which is normally fetched once an hour. The use case where evalDaysLeft reaches 0 and the client goes into offline mode would not benefit of that anyway since it wouldn't have a websocket connection to the server.

If an expired evaluation user is lifted to prod or gets and increased evalDaysLeft, the client would need to either reload the application or call db.cloud.sync() to actively refresh the token and get the new license properties. Expired user will always get their token refreshed when db.cloud.sync() is explicitely called. This behavior should make sure that the application can provide a button or flow to actively update the license status after user has been purchasing a license from the app vendor or in other ways become informed that they got an extended license.

**Comment by b-straub** [comment]
Thank you for the explanation.
