### ISSUE TITLE
How to achieve read-write separation

### ISSUE THREAD

**Issue by GavinZJM** [dexie/Dexie.js#1884]
Let's say I have two transactions one while writing and one while reading， the write transaction before the read transaction，Why does the read transaction get the result after the write transaction is completed。
This scenario in the chat function, websocket transparent transmission of information to us to do local storage operations is very common，What can I do so that the read operation and the write operation do not affect each other

**Comment by dfahlander** [comment]
It's because transactions are ACID compliant. What you seek can be achieved in dexie@4 with liveQuery() as long as your write operatons are not embedded in any explicit 'rw' transaction. A write operation such as Table.put(), Table.update() or Collection.modify() will then hit the liveQuery immediately and not wait for the implicit transaction to commit.

**Comment by GavinZJM** [comment]
> It's because transactions are ACID compliant. What you seek can be achieved in dexie@4 with liveQuery() as long as your write operatons are not embedded in any explicit 'rw' transaction. A write operation such as Table.put(), Table.update() or Collection.modify() will then hit the liveQuery immediately and not wait for the implicit transaction to commit.

Problem solved Thank you very much for your reply
