### ISSUE TITLE
[Nuxt] dexie-cloud-addon not imported correctly by bundler (Cannot find module)

### ISSUE THREAD

**Issue by Stretsh** [dexie/Dexie.js#1885]
I started off with local Dexie, but then moved to Dexie cloud (which is AMAZING, btw). Trying to load the production build, however, gives the following error:

> [nuxt] [request error] [unhandled] [500] Cannot find module '.output/server/node_modules/dexie-cloud-addon/dist/umd/dexie-cloud-addon.min.js' imported from  .output/server/chunks/app/server.mjs

Did some investigation and `.output/server/node_modules/dexie-cloud-addon/dist/` doesn't have a `umd` directory, only a `modern` directory. The project `node_modules` directory does have both umd and modern, but for some reason the bundler only takes the modern folder. I checked the package.json file, and it seems like import (which I use) should call the module in the `modern` directory.

I'm wondering if this is due to how the `package.json` of dexie-cloud-addon was written?

I "fixed" it by setting both dexie and dexie-cloud-addon to not be externalized by vite ssr:

```js
export default defineNuxtConfig({
  ...
  vite: {
   ...
    ssr: {
      noExternal: ['dexie', 'dexie-cloud-addon']
    },
  },
  ...
})
```

Edit: To be clear: I read #1844 which made me think that this _may_ be related...

**Comment by dfahlander** [comment]
Sounds as a bug in the bundler. Nethertheless a pain. In dexie-cloud-addon@4.0.1-beta.32 released for almost a year ago, the package.json exports fields were changed in dexie-cloud-addon for dual export. However, as you've also concluded, the dist/umd directory is present in the package. If nuxt works similar to nextjs, it will transpile the import statements to require and use the umd version of the library on the server but bundle it differently for the browser using the import version of the library. #1844 is not directly related because it regards to the dexie package only.

Googling about this issue generically leads to the same workaround suggested also for different libraries.

There's nothing I can do without a repro but I'm glad you found a workaround.

**Comment by Stretsh** [comment]
Closing this for now. If I find the issue with the bundler, I'll update this for historical purposes.
