### ISSUE TITLE
Get all changes to a table

### ISSUE THREAD

**Issue by sandymcfadden** [dexie/Dexie.js#1904]
I'm looking to be notified and deal with all changes that happen to a specific table. 
[Dexie.Observable ](https://dexie.org/docs/Observable/Dexie.Observable) does just what I need and is working well, but I'm worried about the recommendation to use `liveQuery` instead. Is there a way to get similar results with `liveQuery`?

I've struggled to get something that works similar with live query, especially when something is deleted from the table.
If this is possible is there a sample piece of code someone could share?

**Comment by dfahlander** [comment]
The old `dexie-observable´/`Dexie.Observable` addon does a lot more than observing and that can hurt performance - it tracks all the changes into a table `_changes`. And it's not actively maintained - even though it is still running in our CI tests to verify it does not break in new releases.

You have several options to get notified on changes. The most performant solution (but a bit verbose) option is [Dexie.use()](https://dexie.org/docs/Dexie/Dexie.use()) where you may catch all mutations and have all the freedom to do anything when it happens. It can be used to implement functionality similar to a trigger. The middleware can intercept all the runtime calls to indexedDB including the creation of transactions - so for example, if you intercept the `transaction` method, you can include more tables in the transaction than the caller requests.

Another less verbose option is [Table.hook('deleting')](https://dexie.org/docs/Table/Table.hook('deleting')) where you get notified on deletions of the table you listen on.

Note that both these options will execute in the context of the ongoing transaction - this is important to know because if your code will perform dexie operations, they will inherit the same transaction that performed the delete operation. This can be good if you need to do another operation consistently wheneveer something gets deleted. If that is the case, prefer using Dexie.use(), and when writing to indexedDB, use the downLevel interface passed to your middleware rather than using your Dexie instance again to prevent from endless loops. Also, if the operation needs to have any extra table included in the transaction, make sure to intercept the transaction function in DBCore.

If the purpose is not about triggering extra operations against IndexedDB but to notify the GUI, do a fetch call or other actions not IndexedDB related - or if you may execute arbritary code that do not expect to run inside the ongoing transaction, make sure to break away from the transaction context by calling the action function in a  [Dexie.ignoreTransaction](https://dexie.org/docs/Dexie/Dexie.ignoreTransaction()). This is recommended no matter if you use  [Table.hook('deleting')](https://dexie.org/docs/Table/Table.hook('deleting')) or [Dexie.use()](https://dexie.org/docs/Dexie/Dexie.use()).

**Comment by sandymcfadden** [comment]
Thank you so much @dfahlander this was really helpful! Using the hooks API fit in with the current codebase pretty seamlessly.
