### ISSUE TITLE
REST API endpoint /users changes do not get reflected to the client app

### ISSUE THREAD

**Issue by oyalhi** [dexie/Dexie.js#1939]
We have a stripe webhook on our server, when a customer purchases a subscription, the hook gets triggered. 

After validations, we get the dexie user, change it's type to `prod` or `eval` depending on if they've subscribed or unsubscribed. This operation is successful on the server side.

However, we cannot observe the user type being updated in our client app. Even after refreshes customer still shows as `eval`. Only after log off and log back in does the user correctly reflect the change.

Is this a known bug? Or are there alternative ways to change user's type in a way that will be reflected on the client side (almost) immediately?

**Comment by dfahlander** [comment]
Yes, I am aware of this. The reason is that the prod/eval property comes from the JWT and old eval token is still valid so it's not forcibly refreshed unless eval was expired. We probably need a method in db.cloud to forcibly refresh the token. Before this is in place, one workaround is to do the following:

```ts
db.$logins.toCollection().modify({accessTokenExpiration: 1});
```

This will make dexie-cloud believe it needs to refresh its token.

**Comment by oyalhi** [comment]
Calling the above seems to work; however, works only on the device that we called it from. On user's other devices token is still not refreshed. Is there a workaround that we can call from the server side to force refresh tokens in all devices that user has logged in?

Also, I've tried delaying the call above to avoid errors; however, I still get these, 1 warning & 1 error:

![ScreenShot 2024-03-31 at 15 26 22@2x](https://github.com/dexie/Dexie.js/assets/57917316/82d801b3-7237-4727-b348-a36ed3511008)

**Comment by dfahlander** [comment]
The cloud service (staging) is now updated to push out any updates of the user license status so that all connected clients get it reflected immediately. However, if a user's license has expired, it will not keep an open connection to the cloud anymore and the only way to refresh the status of the user is by calling db.cloud.sync().

The workaround I proposed earlier should not be used since it is not needed anymore.

**Comment by oyalhi** [comment]
Thank you David, this was the last missing piece for me and works like a charm. Below is a short demo using Stripe, albeit low quality due to size limitations. I no longer observe any errors in the console logs during the operation.

I call `db.cloud.sync();` regardless if it's an upgrade or downgrade, I hope that's ok.

Database version shows as `1.4.14` but still works as expected.

https://github.com/dexie/Dexie.js/assets/57917316/a0e637ce-38fc-455a-a217-d7b7fc9c375a

![ScreenShot 2024-04-10 at 08 18 34@2x](https://github.com/dexie/Dexie.js/assets/57917316/1804dff1-3a2e-48b3-9c33-ed8e577ad2ae)

**Comment by bennieforss** [comment]
@oyalhi Looking really good. Dexie Cloud has become really powerful with these new updates.

**Comment by naton** [comment]
Looks very good indeed. Anyone building something similar for [Paypal subscriptions](https://developer.paypal.com/docs/api/subscriptions/v1/)?

**Comment by dfahlander** [comment]
Closing as this was implemented back in April
