### ISSUE TITLE
Dexie Cloud Manager - "Manage users" error

### ISSUE THREAD

**Issue by b-straub** [dexie/Dexie.js#1992]
I have four test databases created for development. Two are working fine in Dexie Cloud Manager and I can manage the users. For the two others with exact same settings "Manage users" fails with "403 (Forbidden)". What might be the reason?

**Comment by dfahlander** [comment]
Please send me the urls of the 2 failing databases and I can troubleshoot it (you can send and email to david(at)dexie.org)

**Comment by dfahlander** [comment]
Thanks for this finding. It turned out the problems with the failing DB was that the DB was configured to deny all unknown users (not explicitely listed) and the owner account you used to login to Dexie Cloud Manager had not yet used the database and was therefore not yet listed. The problem was that Dexie Cloud Manager was also denied to authenticate against the database with that account.

<img width="1126" alt="image" src="https://github.com/dexie/Dexie.js/assets/6791329/2daba898-12b3-43fa-a067-ac970a23655c">

This situation could be resolved by temporarily allowing all unknown users, click the Manage Users button (which would add your account) and then configure back to the reject all unknown. Though, this was not working on one of the apps because it had some reject patterns configured and the manager did not reset those when selecting 'Automatically create evaluation accounts for new users (default)' again. I could heal it manually though, but it's good this was discoverd so I can fix the bug in Dexie Cloud Manager.
