### ISSUE TITLE
Can't put middleware higher than Dexie Cloud

### ISSUE THREAD

**Issue by tylermercer** [dexie/Dexie.js#2047]
I have a custom middleware that I want to run only on user operations and not on operations that are performed by the Dexie Cloud addon. E.g. if the user creates an entity in the app, this middleware should be invoked. When that entity gets synced to another device, it should _not_ be, even though it's being created there (by `dexie-cloud-addon`) for the first time.

I tried to set the `level` param of my custom middleware to `2` [as was done in this POC of using dexie-encrypted with Dexie Cloud](https://github.com/dexie/Dexie.js/issues/1604#issuecomment-1237065115), but it doesn't seem to be working; the middleware is still called on operations that are triggered by Dexie Cloud.

What am I missing?

**Comment by dfahlander** [comment]
The level param will only order the middleware differently to be called before or after other middlewares. There is no way to generically jump over another middleware since the down-level (or next) middleware has to be called to eventually reach the lowest level.

The sync engine does not origin from within a middleware. Middleware is there to track mutations and other things though. But I think you should be able to detect whether an operation was initiated by the user or from a sync operation. If trans.disableChangeTracking is true (that property is not typed so you'd have to `// @ts-ignore` it), it means that all the operations being performed are results from a sync operation and not locally performed.

**Comment by dfahlander** [comment]
> Are there any cases where an entity is added by the dexie-cloud-addon but it doesn't set `disabledChangeTracking` to true? 🤔

Yes when storing dexie-cloud data in tables starting with `$` in their name ($logins, $baserevs etc), then it does not need to set this property because those tables aren't tracked. But any change in synced application defined tables shall for sure have this property set when being updated.

**Comment by tylermercer** [comment]
That makes sense! Thanks for your help.
