### ISSUE TITLE
Cache error after bulkPut failures

### ISSUE THREAD

**Issue by Monara** [dexie/Dexie.js#2058]
We've encountered an error in v4.0.8 that seems to happen after (expected) bulkPut failed operations. Error happens here, operation is null:

```
var ops = tblCache.optimisticOps.filter(function(op) {
  return op.trans === idbtrans;
});
```
[link to source file](https://github.com/dexie/Dexie.js/blob/e41f017b4fb0ddf23d037c44090acc5184b41135/src/live-query/cache/cache-middleware.ts#L55-L57)

Of course, disabling the cache as suggested in other recent issues removes the problem.

**Comment by dfahlander** [comment]
I created a repro of this but it turned out to actually be working as expected only that liveQueries will emit results optimistically temporarily before making another corrected emit. If this is not desired the query should be done within a readonly transaction within the querier:

```ts
useLiveQuery(() => {
  return db.transaction('r', 'myTable', () => db.myTable.toArray());
});
```

The repro I created turned out to emit the bulkPut values initially and then within a millisecond yet again emit a correct result. However, I did improve the optimistic part to avoid certain duplicates - specifically duplicates of the primary key unique constraint in case the previous result had a duplicate but the actual constraint state isn't known until the actual update happens in the database.

Conclusions:
* Optimistic emittions from liveQueries can be faulty temporarily when the cache is enabled and this is the nature of optimistic updates.
* I could improve the code some for obvious dups of primary keys in optimistic results but this is only cosmetic.
* To disable optimistic updates, either use { cache: 'disabled' } or let the liveQuery do it's query in a transaction - which will opt-out that particular query from being optimistic.
