### ISSUE TITLE
Error in Dexie 4: Failed to execute 'cmp' on 'IDBFactory': The parameter is not a valid key

### ISSUE THREAD

**Issue by probert94** [dexie/Dexie.js#2064]
I recently updated Dexie from 3.2.6 to 4.0.8. Since then one of my queries throws the error `Failed to execute 'cmp' on 'IDBFactory': The parameter is not a valid key` in certain cases.
The query looks like this:
```
await this.table("table")
    .where({foreignKey1: "1", foreignKey2: "1"})
    .toArray()
```
After some investigation I found, that the error is thrown, if there are entries for "foreignKey1" where "foreignKey2" is "null".
In my case the foreignKey1 is never "null" so switching order of the fields in "where" solves the error and this code works:
```
await this.table("table")
    .where({foreignKey2: "1", foreignKey1: "1"})
    .toArray()
```
As I did not define a compound index for the two fields it shows a warning but returns the correct results.

**Comment by dfahlander** [comment]
Thanks. The behaviour should be fixed by switching to using [cmp.ts](https://github.com/dexie/Dexie.js/blob/master/src/functions/cmp.ts) instead of idb.cmp() at [this location](https://github.com/dexie/Dexie.js/blob/master/src/classes/table/table.ts#L151). By using cmp.ts (which is also much faster that indexedDB.cmp()), a null comparision returns NaN instead of throwing, which is what would be correct here.

**Comment by dfahlander** [comment]
Resolved in #2076

**Comment by Nedi11** [comment]
When will the package be updated with this fix

**Comment by dfahlander** [comment]
A new release of dexie will probably be out tomorrow with the latest from master.
